// Auto-generated by Scripts/export-abi.js — do not edit manually
import CommitteeManagerAbi from './CommitteeManager.json';
import GreenTokenAbi from './GreenToken.json';
import RewardTokenAbi from './RewardToken.json';
import AMMPoolAbi from './AMMPool.json';
import VerifierManagerAbi from './VerifierManager.json';
import ActivityVerificationAbi from './ActivityVerification.json';
import RewardRedemptionAbi from './RewardRedemption.json';
 
export const ABIs = {
  CommitteeManager: CommitteeManagerAbi.abi,
  GreenToken: GreenTokenAbi.abi,
  RewardToken: RewardTokenAbi.abi,
  AMMPool: AMMPoolAbi.abi,
  VerifierManager: VerifierManagerAbi.abi,
  ActivityVerification: ActivityVerificationAbi.abi,
  RewardRedemption: RewardRedemptionAbi.abi,
} as const;
 
export type ContractName = keyof typeof ABIs;
