const fs = require("fs");
const path = require("path");
 
const CONTRACTS = [
  "CommitteeManager",
  "GreenToken",
  "RewardToken",
  "AMMPool",
  "VerifierManager",
  "ActivityVerification",
  "RewardRedemption",
];
 
const PROJECT_ROOT = path.join(__dirname, "..");
 
// Hardhat artifacts
const ARTIFACTS_DIR = path.join(PROJECT_ROOT, "artifacts", "Contracts");
 
const FRONTEND_ABI_DIR = path.join(PROJECT_ROOT, "Frontend", "contracts", "abis");
 

const DEPLOYMENTS_DIR = path.join(PROJECT_ROOT, "deployments");
 

const FRONTEND_DEPLOYMENTS_DIR = path.join(PROJECT_ROOT, "Frontend", "contracts");
 
function log(emoji, msg) {
  console.log(`${emoji}  ${msg}`);
}
 
function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    log("📁", `Created: ${path.relative(PROJECT_ROOT, dir)}`);
  }
}
 

function main() {
  log("Starting ABI export...");
  console.log("");
 
  // 0. 检查 artifacts 目录是否存在
  if (!fs.existsSync(ARTIFACTS_DIR)) {
    console.error(`❌  artifacts/Contracts directory not found.`);
    console.error(`    Run 'npx hardhat compile' first.`);
    process.exit(1);
  }
 
  // 1. create frontend directories if not exist
  ensureDir(FRONTEND_ABI_DIR);
  ensureDir(FRONTEND_DEPLOYMENTS_DIR);
 
  // 2. export ABIs
  console.log("");
  log("📦", "Exporting ABIs:");
  let exportedCount = 0;
 
  for (const name of CONTRACTS) {
    const artifactPath = path.join(
      ARTIFACTS_DIR,
      `${name}.sol`,
      `${name}.json`
    );
 
    if (!fs.existsSync(artifactPath)) {
      console.error(`  ❌  ${name}.json not found at ${artifactPath}`);
      console.error(`      Did you run 'npx hardhat compile'?`);
      continue;
    }
 
    // read artifact
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    const minimal = {
      contractName: name,
      abi: artifact.abi,
    };
 
    const outPath = path.join(FRONTEND_ABI_DIR, `${name}.json`);
    fs.writeFileSync(outPath, JSON.stringify(minimal, null, 2));
 
    const size = (fs.statSync(outPath).size / 1024).toFixed(1);
    console.log(`  ✓  ${name}.json (${size} KB)`);
    exportedCount++;
  }
 
  // 3. copy sepolia.json to frontend
  console.log("");
  log("📋", "Copying deployment files:");
 
  const deploymentFiles = fs.existsSync(DEPLOYMENTS_DIR)
    ? fs.readdirSync(DEPLOYMENTS_DIR).filter((f) => f.endsWith(".json"))
    : [];
 
  if (deploymentFiles.length === 0) {
    console.log(`  ⚠️   No deployment JSON files in deployments/.`);
    console.log(`      Run 'npx hardhat run Scripts/deploy/deploy_all.js --network sepolia' first.`);
  } else {
    for (const file of deploymentFiles) {
      const src = path.join(DEPLOYMENTS_DIR, file);
      const dst = path.join(FRONTEND_DEPLOYMENTS_DIR, file);
      fs.copyFileSync(src, dst);
      console.log(`  ✓  ${file}`);
    }
  }
 
  // 4. generate index.ts
  console.log("");
  log("📝", "Generating TypeScript index:");
 
  const indexContent = `// Auto-generated by Scripts/export-abi.js — do not edit manually
${CONTRACTS.map(
    (name) => `import ${name}Abi from './${name}.json';`
  ).join("\n")}
 
export const ABIs = {
${CONTRACTS.map((name) => `  ${name}: ${name}Abi.abi,`).join("\n")}
} as const;
 
export type ContractName = keyof typeof ABIs;
`;
 
  const indexPath = path.join(FRONTEND_ABI_DIR, "index.ts");
  fs.writeFileSync(indexPath, indexContent);
  console.log(`  ✓  index.ts`);
 
  // 5. summary
  console.log("");
  log("🎉", `Done! Exported ${exportedCount}/${CONTRACTS.length} contracts.`);
  console.log("");
  console.log("Frontend can now import:");
  console.log(`  import { ABIs } from '@/Contracts/abis';`);
  console.log(`  import deployment from '@/Contracts/sepolia.json';`);
  console.log("");
}
 
main();
